### ISSUE TITLE
Execution speed on ARM Cortex-M4F

### ISSUE THREAD

**Issue by larschristensen** [DusKing1/vqf-c#1]
Looks like an interesting project!

Do you have any insight into the execution speed of this C implementation running on ARM Cortex-M4F?

**Comment by DusKing1** [comment]
I do have some results about execution speed on ARM Cortex-M7F, but better to get @Lozart here to reply to you with the details.

**Comment by Lozart** [comment]
So the hardware and compiler:
- MCU: STM32H7B0 280Mhz
- GCC version: 10.3.1
- Optimization flag: -O3
- FPU: fpv5-d16
- IMU: LSM6DSO with ODR 833Hz
- MAG: LIS2MDL with ODR 50Hz

Running `VQF_MIXED_PRECISION`:
|Function|Time cost|
| :--- | ---: |
|updateGyr|3.40us|
|updateAcc|11.05us|
|updateMag|6.66us|

**Comment by larschristensen** [comment]
> So the hardware and compiler:
> 
> * MCU: STM32H7B0 280Mhz
> * GCC version: 10.3.1
> * Optimization flag: -O3
> * FPU: fpv5-d16
> * IMU: LSM6DSO with ODR 833Hz
> * MAG: LIS2MDL with ODR 50Hz
> 
> Running `VQF_MIXED_PRECISION`:
> 
> Function	Time cost
> updateGyr	3.40us
> updateAcc	11.05us
> updateMag	6.66us

Thanks, that is good info. What algorithm features were enabled for this measurement, i.e. the values of {`restBiasEstEnabled`, `magDistRejectionEnabled`, `motionBiasEstEnabled`}?

Is your experience that running with `VQF_MIXED_PRECISION` is needed? Do you have any execution times for running with `VQF_SINGLE_PRECISION` instead?

**Comment by DusKing1** [comment]
> > So the hardware and compiler:
> > 
> > * MCU: STM32H7B0 280Mhz
> > * GCC version: 10.3.1
> > * Optimization flag: -O3
> > * FPU: fpv5-d16
> > * IMU: LSM6DSO with ODR 833Hz
> > * MAG: LIS2MDL with ODR 50Hz
> > 
> > Running `VQF_MIXED_PRECISION`:
> > 
> > Function	Time cost
> > updateGyr	3.40us
> > updateAcc	11.05us
> > updateMag	6.66us
> 
> Thanks, that is good info. What algorithm features were enabled for this measurement, i.e. the values of {`restBiasEstEnabled`, `magDistRejectionEnabled`, `motionBiasEstEnabled`}?
> 
> Is your experience that running with `VQF_MIXED_PRECISION` is needed? Do you have any execution times for running with `VQF_SINGLE_PRECISION` instead?

In this port/approach, all vqf features are enabled.

And `VQF_SINGLE_PRECISION` will reduce around ~40% execution time compared to `VQF_MIXED_PRECISION`. We are planning to do precision tests about these two cases.

**Comment by larschristensen** [comment]
Thanks for the info, closing.
